version: '3.8'

services:
    starwars-api:
        build: .
        ports:
            - '${EXTERNAL_PORT:-6969}:${INTERNAL_PORT:-8000}'
        env_file:
            - .env
        volumes:
            - .:/app
        command: uvicorn app.main:app --host 0.0.0.0 --port ${INTERNAL_PORT:-8000} --reload

    starwars-cli:
        build: .
        env_file:
            - .env
        environment:
            - API_BASE_URL=${API_BASE_URL:-http://starwars-api:8000}
        volumes:
            - .:/app
        depends_on:
            - starwars-api
        command: tail -f /dev/null
        profiles:
            - cli
